//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PunjabLab
{
    using System;
    using System.Collections.Generic;
    
    public partial class report
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string age { get; set; }
        public string sex { get; set; }
        public System.DateTime rpt_date { get; set; }
        public string refferby { get; set; }
        public string hb { get; set; }
        public string tlc { get; set; }
        public string ref_by { get; set; }
        public string polymorph { get; set; }
        public string lymphocyte { get; set; }
        public string eosinophil { get; set; }
        public string monocyte { get; set; }
        public string basophil { get; set; }
        public string mp { get; set; }
        public string esr { get; set; }
        public string bt { get; set; }
        public string ct { get; set; }
        public string abs_eosinophil { get; set; }
        public string platelet { get; set; }
        public string HBs_Ag { get; set; }
        public string rafactor { get; set; }
        public string vdrltest { get; set; }
        public string toxoplasma_igm { get; set; }
        public string hiv { get; set; }
        public string hcv { get; set; }
        public string dengue { get; set; }
        public string ns_i { get; set; }
        public string igm { get; set; }
        public string igg { get; set; }
        public string blod_group_rh { get; set; }
        public string pregnancy_test { get; set; }
        public string to120 { get; set; }
        public string to140 { get; set; }
        public string to180 { get; set; }
        public string to1160 { get; set; }
        public string to1320 { get; set; }
        public string to1640 { get; set; }
        public string th120 { get; set; }
        public string th140 { get; set; }
        public string th180 { get; set; }
        public string th1160 { get; set; }
        public string th1320 { get; set; }
        public string th1640 { get; set; }
        public string ah120 { get; set; }
        public string ah140 { get; set; }
        public string ah180 { get; set; }
        public string ah1160 { get; set; }
        public string ah1320 { get; set; }
        public string ah1640 { get; set; }
        public string bh120 { get; set; }
        public string bh140 { get; set; }
        public string bh180 { get; set; }
        public string bh1160 { get; set; }
        public string bh1320 { get; set; }
        public string bh1840 { get; set; }
        public string BloodSugarFasting { get; set; }
        public string BloodSugarR { get; set; }
        public string BloodSugarPP { get; set; }
        public string BloodUrea { get; set; }
        public string SerumCreatinine { get; set; }
        public string UricAcid { get; set; }
        public string BloodCholesterol { get; set; }
        public string HDLCholesterol { get; set; }
        public string Triglycerides { get; set; }
        public string L_D_L { get; set; }
        public string V_L_D_L { get; set; }
        public string SerumBilirubin { get; set; }
        public string Direct { get; set; }
        public string InDirect { get; set; }
        public string SGPT { get; set; }
        public string SGOT { get; set; }
        public string SerumAlkalinePhosphatase { get; set; }
        public string Protein { get; set; }
        public string Albumins { get; set; }
        public string Globulin { get; set; }
        public string BileSalt { get; set; }
        public string BilePigment { get; set; }
        public string UrineSugar { get; set; }
        public string Albumin { get; set; }
        public string PusCells { get; set; }
        public string R_B_C { get; set; }
        public string UricAcids { get; set; }
        public string EpithelialCell { get; set; }
        public string Oxalate { get; set; }
        public string Volume { get; set; }
        public string Colour { get; set; }
        public string Viscosity { get; set; }
        public string SpermCount { get; set; }
        public string ActiveSperms { get; set; }
        public string SluggishSperms { get; set; }
        public string Dead { get; set; }
        public string PusCell { get; set; }
        public string AnyOther { get; set; }
    }
}
